spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4864
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    generate-ddl: true